### ISSUE TITLE
Suppress second player mention when giving out rewards

### ISSUE THREAD

**Issue by 7uci3n** [a-h-i/progress-bot#6]
As a player, I would like to be pinged only once, when a DM gives rewards to me.

The bot asks for a confirmation and mentions the players again. This can and will become pretty annoying I would say. Although most of the time the players will be online at that time anyways, I don't think we need that explicit mention there if avoidable.
The DM mention is fine since they should be in the current channel.
```
@(Samson) Mia 5.12.33, Please reply with yes to confirm rewarding 100 gold and 0 experience to:
@(Samson) Mia 5.12.33 Mia Moonweaver <-- THIS
```

**Comment by a-h-i** [comment]
Fixed for v1.1
